-- CREATE SCHEMA myschema;

-- CREATE TABLE myschema.DOG (
--    ID INTEGER PRIMARY KEY NOT NULL ,
--    NAME VARCHAR(16) NOT NULL,
--    BREED VARCHAR(32) NOT NULL
-- );

CREATE TABLE DOG
(
   ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR(16) NOT NULL,
   BREED VARCHAR(32) NOT NULL
);